export const PKG_PREFIX = '@zzui-plus'
export const PKG_NAME = 'zzui-plus'
export const PKG_CAMELCASE_NAME = 'ZzuiPlus'
export const PKG_CAMELCASE_LOCAL_NAME = 'ZzuiPlusLocale'
export const PKG_BRAND_NAME = 'Zzui Plus'
